//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonsterNew
    {
        public int MonsterID { get; set; }
        public string MonsterName { get; set; }
        public int MonsterHP { get; set; }
        public int MonsterATK { get; set; }
        public int MonsterExp { get; set; }
    }
}
